//Se importa el array de ciudades, es un archivo externo
export const colombianCities = [
    "Aguachica, Colombia",
    "Apartadó, Colombia",
    "Arauca, Colombia",
    "Armenia, Colombia",
    "Barrancabermeja, Colombia",
    "Barranquilla, Colombia",
    "Bello, Colombia",
    "Bogotá, Colombia",
    "Bucaramanga, Colombia",
    "Buenaventura, Colombia",
    "Buga, Colombia",
    "Cali, Colombia",
    "Cartagena, Colombia",
    "Cartago, Colombia",
    "Caucasia, Colombia",
    "Chía, Colombia",
    "Ciénaga, Colombia",
    "Cúcuta, Colombia",
    "Dosquebradas, Colombia",
    "Duitama, Colombia",
    "Envigado, Colombia",
    "Espinal, Colombia",
    "Facatativá, Colombia",
    "Florencia, Colombia",
    "Floridablanca, Colombia",
    "Fusagasugá, Colombia",
    "Girardot, Colombia",
    "Girón, Colombia",
    "Ibagué, Colombia",
    "Inírida, Colombia",
    "Ipiales, Colombia",
    "Itagüí, Colombia",
    "Jamundí, Colombia",
    "Leticia, Colombia",
    "Lorica, Colombia",
    "Magangué, Colombia",
    "Maicao, Colombia",
    "Malambo, Colombia",
    "Manizales, Colombia",
    "Medellín, Colombia",
    "Mitú, Colombia",
    "Mocoa, Colombia",
    "Montería, Colombia",
    "Neiva, Colombia",
    "Ocaña, Colombia",
    "Palmira, Colombia",
    "Pasto, Colombia",
    "Pereira, Colombia",
    "Piedecuesta, Colombia",
    "Pitalito, Colombia",
    "Popayán, Colombia",
    "Puerto Carreño, Colombia",
    "Puerto Nariño, Colombia",
    "Quibdó, Colombia",
    "Riohacha, Colombia",
    "Rionegro, Colombia",
    "San Andrés, Colombia",
    "San José del Guaviare, Colombia",
    "Santa Marta, Colombia",
    "Santander de Quilichao, Colombia",
    "Saravena, Colombia",
    "Sincelejo, Colombia",
    "Soacha, Colombia",
    "Sogamoso, Colombia",
    "Soledad, Colombia",
    "Tuluá, Colombia",
    "Tumaco, Colombia",
    "Tunja, Colombia",
    "Valledupar, Colombia",
    "Villa del Rosario, Colombia",
    "Villavicencio, Colombia",
    "Yopal, Colombia",
    "Yumbo, Colombia",
    "Zipaquirá, Colombia"
];
